name: Java CI

on:
  push:
    branches:
      - 'java/atividade01/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo-fonte
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Clonar reposit칩rio de teste privado
        uses: actions/checkout@v2
        with:
          repository: Jose-Isaac/monitoria-estrutura-de-dados
          path: tests  # Nome da pasta onde o reposit칩rio privado ser치 clonado

      - name: Compilar e rodar testes
        run: |
          cp ./tests/monitoria-estrutura-de-dados/atividade01/Test_atividade01.java ./src/atividade01
          cp ./tests/monitoria-estrutura-de-dados/atividade01/*.jar ./src/atividade01
          javac Busca_IF.java Busca.java .\BrincandoComBusca.java
          javac -cp .:junit.jar:hamcrest-core.jar your_test_file.java
          java -cp .:junit.jar:hamcrest-core.jar org.junit.runner.JUnitCore YourTestClass
