name: Java CI

on:
  push:
    branches:
      #      - main
      - 'java/atividade/03/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Clonar repositório de teste privado
        uses: actions/checkout@v4
        with:
          repository: Jose-Isaac/monitoria-estrutura-de-dados
          token: ${{ secrets.TOKEN_TO_ACCESS_PRIVATE_REPO_WITH_TEST }}
          path: tests

      - name: Copiar teste lista encadeada
        run: |
          cp tests/atividade03/Test_ListaEncadeada.java atividade03/src/test/java/br/edu/uepb/eda/atividade03

      - name: Copiar teste fila
        run: |
          cp tests/atividade03/Test_Fila.java atividade03/src/test/java/br/edu/uepb/eda/atividade03

      - name: Copiar teste pilha
        run: |
          cp tests/atividade03/Test_Pilha.java atividade03/src/test/java/br/edu/uepb/eda/atividade03
          
          

      - name: Compilar e rodar testes com Gradle
        run: |
          cd atividade03
          chmod +x ./gradlew
          ./gradlew test