name: Java CI

on:
  push:
    branches:
      #      - main
      - 'java/atividade/04/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Clonar repositório de teste privado
        uses: actions/checkout@v4
        with:
          repository: Jose-Isaac/monitoria-estrutura-de-dados
          token: ${{ secrets.TOKEN_TO_ACCESS_PRIVATE_REPO_WITH_TEST }}
          path: tests

      - name: Copiar teste tabala hash
        run: |
          cp tests/atividade04/Test_TabelaHash.java atividade04/src/test/java/br/edu/uepb/eda/atividade04

      - name: Copiar teste bst
        run: |
          cp tests/atividade04/Test_BST.java atividade04/src/test/java/br/edu/uepb/eda/atividade04

      - name: Compilar e rodar testes com Gradle
        run: |
          cd atividade04
          chmod +x ./gradlew
          ./gradlew test