on:
  pull_request_target:
    types:
      - opened

jobs:
  run_if:
    if:  startsWith(github.head_ref, 'java/atividade/01/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Clonar repositório de teste privado
        uses: actions/checkout@v2
        with:
          repository: Jose-Isaac/monitoria-estrutura-de-dados
          token: ${{ secrets.TOKEN_TO_ACCESS_PRIVATE_REPO_WITH_TEST }}
          path: tests

      - name: Copiar arquivo de teste
        run: |
          mkdir atividade01/src/test atividade01/src/test/java atividade01/src/test/java/br atividade01/src/test/java/br/edu atividade01/src/test/java/br/edu/uepb atividade01/src/test/java/br/edu/uepb/eda atividade01/src/test/java/br/edu/uepb/eda/atividade01
          cp tests/atividade01/Test_atividade01.java atividade01/src/test/java/br/edu/uepb/eda/atividade01

      - name: Compilar e rodar testes com Gradle
        run: |
          cd atividade01
          ./gradlew test
